### PR TITLE
Pobrien/refactor scope

### PR DESCRIPTION
**Pull request by bolddane**
Refactor small changes.

/cc @zendesk/zendesk-radar

### Steps to merge
 - [ ] :+1: of the team

### References
 - Jira link: 

### Risks
 - None

### CODE REVIEW

**Comment by vanchi-zendesk** [comment]
:+1: when radar tests pass.

**Comment by lucasefe** [comment]
:+1:

**Comment by vanchi-zendesk** [comment]
https://github.com/zendesk/radar/pull/151#

**Comment by vanchi-zendesk** [comment]
https://travis-ci.org/zendesk/radar/builds/74607932

**Pull request merged**
